daysUntilStale: 62
daysUntilClose: 14
exemptLabels:
  - pinned
  - security
staleLabel: :coffin: stale
markComment: >
  :derelict_house:
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
