name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - run: go build -v termage.go

    - name: Test and Generate Coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
