name: Release
on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get Version
        run: echo "::set-output name=VERSION::$(git describe --tags)"
        id: version
      - name: Get Output Filename
        run: echo "::set-output name=FILENAME::termage-${{ matrix.os }}${{ matrix.os == 'windows-latest' ? '.exe' : '' }}"
        id: filename
      - name: Build
        run: go build -o "${{ steps.filename.outputs.FILENAME }}" ldflags "-X main.version=${{ steps.version.outputs.VERSION }}" termage.go
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.FILENAME }}
