name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo "::set-output name=VERSION::$(git describe --tags)"
        id: version


  release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get Release Notes
        run: 'echo "::set-output name=RELEASE_NOTES::$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)"'
        id: release-notes
      - name: Fail on empty release notes
        run: |
          echo "::error ::Empty release notes"
          exit 1
        if: ${{ steps.release-notes.outputs.RELEASE_NOTES == '' }}
      - name: Set Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release-notes.outputs.RELEASE_NOTES }}

  build:
    runs-on: ${{ matrix.os }}-latest
    needs:
      - get-version
      - release-notes
    env:
      TERMAGE_VERSION: ${{ needs.get-version.outputs.VERSION }}
      OUTPUT_FILENAME: termage-${{ matrix.os }}${{ matrix.os == 'windows' && '.exe' || '' }}
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Build
        run: go build -o "${{ env.OUTPUT_FILENAME }}" -ldflags "-X main.version=${{ env.TERMAGE_VERSION }}" termage.go
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.OUTPUT_FILENAME }}
