name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set Variables
        id: variables
        uses: spenserblack/actions-set-output@v0.1
        with: |
          VERSION=$(git describe --tags)
          FILENAME=termage-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Build
        run: go build -o "${{ steps.variables.outputs.FILENAME }}" -ldflags "-X main.version=${{ steps.variables.outputs.VERSION }}" termage.go
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.FILENAME }}
