name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: echo "::set-output name=VERSION::$(git describe --tags)"
        id: version


  release-notes:
    name: Add Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - name: Set Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES

  release-assets:
    name: Upload Release Assets
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    needs:
      - get-version
      - release-notes
    env:
      TERMAGE_VERSION: ${{ needs.get-version.outputs.VERSION }}
      OUTPUT_FILENAME: termage-${{ matrix.os }}${{ matrix.os == 'windows' && '.exe' || '' }}
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Build
        run: go build -o "${{ env.OUTPUT_FILENAME }}" -ldflags "-X main.version=${{ env.TERMAGE_VERSION }}" termage.go
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.OUTPUT_FILENAME }}
