name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.output-step.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: spenserblack/actions-set-output@v1
        id: output-step
        with:
          variables: |
            VERSION=$(git describe --tags)

  build:
    runs-on: ${{ matrix.os }}
    needs: get-version
    env:
      TERMAGE_VERSION: ${{ needs.get-version.outputs.VERSION }}
      OUTPUT_FILENAME: termage-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Build
        run: go build -o "${{ env.OUTPUT_FILENAME }}" -ldflags "-X main.version=${{ env.TERMAGE_VERSION }}" termage.go
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.OUTPUT_FILENAME }}
